### ISSUE TITLE
OpenAPI SecurityValidator: Configuration 

### ISSUE THREAD

**Issue by predic8** [membrane/api-gateway#1012]
With validateSecurity="yes" alone nothing happens. To make it work validateRequests="yes" is at the same time required.

Alternatives:

a.) Activate validateRequests automatically with setting validateSecurity

b.) Do not start when validateRequests=no and show an error

c.) Add a flag security to ValidationError. If   validateSecurity is yes, validate allways requests. Look at the errors. If there is no security error let it pass. If there is a security error return error message to the caller.

**Comment by predic8** [comment]
I would opt for c.) but I'am not sure. Reason: Most intuitive for the user.

**Comment by t-burch** [comment]
What about an enum like:
`validationScheme="<REQUEST|RESPONSE|BOTH|SECURED_REQUEST|SECURED_BOTH>"`
