### ISSUE TITLE
Cookbook Examples for membrane-api.io

### ISSUE THREAD

**Issue by predic8** [membrane/api-gateway#1086]
Sub Heading 

6. API Gateway Recipes

Like:

- [x] How to set an HTTP Header - API Gateway Cookbook
- [x] How to change the status code of an response
- [x] How to change an error Message from a Backend
- [x] How to return a static JSON Document
- [x] Redirekt to SSL
- [x] Rewrite host, port, path of openapi
- [x] Remove HTTP Headers
- ...

**Comment by t-burch** [comment]
Further recipe ideas:
How to rate limit
How to validate OpenAPI
How to add CORS headers to responses
How to implement rate limiting
How to implement basic authentication
How to log API requests and responses
How to route requests based on URL path
How to cache API responses?
How to implement IP whitelisting / acl
