### ISSUE TITLE
Refactor Tests:

### ISSUE THREAD

**Issue by predic8** [membrane/api-gateway#1104]
is com.predic8.membrane.servlet.test.IntegrationTests still in use?

**Comment by t-burch** [comment]
Tests are designed to not start membrane but rely on externally running instance. Does not seem to have a proxies.xml for it so they can't be run

**Comment by rrayst** [comment]
The `IntegrationTests` suite is launched as part of the `integration-test` Maven goal.

**Comment by rrayst** [comment]
> The `IntegrationTests` suite is launched as part of the `integration-test` Maven goal.

This is true for the `core` (=`core` package) as well as the `war` (=`servlet` package) module.
