### ISSUE TITLE
OpenAPI response validation returns internal server error if declared response header is not present

### ISSUE THREAD

**Issue by comrt** [membrane/api-gateway#1119]
If an OpenAPI document declares a response header with _validateResponses_ set to true in the proxies.xml and the backend service does not return this header, the validation fails with:

`"message": "Cannot invoke \"java.lang.Boolean.booleanValue()\" because the return value of \"io.swagger.v3.oas.models.headers.Header.getRequired()\" is null"`

**Comment by predic8** [comment]
Hi @comrt,
thanks for reporting. We fixed this in version 5.5.2. If you experience that behaviour still in 5.5.2 please tell us.

**Comment by rrayst** [comment]
@predic8 The next release is 5.5.3.

**Comment by predic8** [comment]
@comrt you are right. We created a pr for that:

https://github.com/membrane/api-gateway/pull/1120

In the next release 5.5.3 it will be fixed.
