### ISSUE TITLE
`examples/openapi/README.md` does not work

### ISSUE THREAD

**Issue by rrayst** [membrane/api-gateway#1163]
The README suggests to use

```
   <api port="2000">
       <apiDocs />
   </api>

    <api port="2001">
        <openapi location="https://developer.lufthansa.com/swagger/export/21516"/>
    </api>
```

and then open http://localhost:2000/ in a web browser. If you do that and click "Try it out"+"Execute request", a request will be issued to localhost:2000 (not going to the Lufthansa API) and Membrane will respond with a JSON list of the APIs.

**Comment by predic8** [comment]
Request should go to http://localhost:2000/some-path and the it should be forwarded to dev...
