### ISSUE TITLE
why doesn't the 'test' condition go through `LanguageSupport`?

### ISSUE THREAD

**Issue by rrayst** [membrane/api-gateway#1199]
@predic8 why doesn't the 'test' condition go through `LanguageSupport`?

All Spel Expressions (as currently implemented in the master branch and suggested by this pull request) are always *interpreted*.

Adding these expressions to a rule key causes a slow down in *all* incoming requests.

Allowing the user to switch to Groovy would therefore increase performance significantly.

_Originally posted by @rrayst in https://github.com/membrane/api-gateway/issues/1185#issuecomment-2232797506_

**Comment by t-burch** [comment]
@rrayst we should enable the SpEL compiler, which increases the performance massively

**Comment by predic8** [comment]
Use SpEL compiler
