### ISSUE TITLE
Make it possible to disable groovy templating in template plugin

### ISSUE THREAD

**Issue by t-burch** [membrane/api-gateway#1201]
If template should be the only way to return static text, make the groovy templating a default true option, so that when using characters like dollar signs inside JSON (as an example for OData), that it doesn't throw groovy templating errors and require escaping the dollar sign

**Comment by predic8** [comment]
Sketch concept here first

**Comment by t-burch** [comment]
```xml
<static contentType="application/json" pretty="true"> <!-- Same as template but without templating -->
  {
    "foo": "bar"
  }
</static>
```

**Comment by christiangoerdes** [comment]
or:

```xml
<api port="2000">
    <return>
        {
            "foo": "bar"
        }
    </return>
</api>
```

**Comment by predic8** [comment]
pretty and JSON?
