### ISSUE TITLE
Documentation: How to start Membrane without installing it!

### ISSUE THREAD

**Issue by predic8** [membrane/api-gateway#1215]
try:

jbang --main com.predic8.membrane.core.Starter org.membrane-soa:starter:5.5.4 -c "file:///Users/thomas/tmp/membrane-api-gateway-5.4.2-SNAPSHOT/conf/proxies.xml"

as a receipe for membrane-api.io

See: https://www.jbang.dev/documentation/guide/latest/usage.html#running-jars

Maybe we can declare com.predic8.membrane.core.Starter  as main to make it shorter.

**Comment by predic8** [comment]
link to installing jbang

**Comment by predic8** [comment]
ohne config show help 

Options:
- c

**Comment by christiangoerdes** [comment]
The pull request on GitLab is ready and will be merged once the newest release is published.
