### ISSUE TITLE
Pre-Release vs Latest

### ISSUE THREAD

**Issue by precoder** [membrane/api-gateway#1239]
Hello,

We want to integrate the newest Version of api-gateway but I have seen last 3 releases on the Release Page are marked as "Pre-Release".

https://github.com/membrane/api-gateway/releases

Is there a known reason for avoding these versions for now? 
Can we integrate for example 5.7.1(pre-release) instead of 5.5.4(latest)?

**Comment by t-burch** [comment]
@precoder they should generally be stable and can be used, but the new features might still be tweaked until the full release.
