### ISSUE TITLE
ElasticSearch Exchange Store Body Format

### ISSUE THREAD

**Issue by predic8** [membrane/api-gateway#1286]
See: https://github.com/membrane/api-gateway/discussions/1285

- In case of JSON mediatype do not base64 encode
- Have a look why the body is not stored

**Comment by 1234abd** [comment]
This might help:This file might fix it

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
If you don't have the c compliator, install it.(gcc or clang)

**Comment by predic8** [comment]
@christiangoerdes 
Before starting plz contact me
