### ISSUE TITLE
OpenAPI validation with schema references not working

### ISSUE THREAD

**Issue by paulhyo** [membrane/api-gateway#1317]
Hello, I'm using a OpenAPI Schema with references on other schemas defined in a subdirectory. This structure is valid, generated API-Doc and request / response validation are not working in Membrane

Membrane version: 5.5.4

OpenAPI:
[code-service-openapi-0.99.0-SNAPSHOT.zip](https://github.com/user-attachments/files/17539415/code-service-openapi-0.99.0-SNAPSHOT.zip)

Proxies.xml
[proxies.xml.txt](https://github.com/user-attachments/files/17539568/proxies.xml.txt)

LOG:
[membrane-test-error-log.txt.txt](https://github.com/user-attachments/files/17539598/membrane-test-error-log.txt.txt)
[membrane-log.txt.txt](https://github.com/user-attachments/files/17539600/membrane-log.txt.txt)

API-Doc Printscreen
<img width="943" alt="Membrane_APIDocs_error" src="https://github.com/user-attachments/assets/e670c9b0-030e-4a00-8195-d1005ec24177">

**Comment by predic8** [comment]
Hi,
unfortunately URI resolution is very complicated. So we decided not to support it. Instead you can bundle your OpenAPI parts into one document and use that to deploy. You can use redocly from instance:

npx @redocly/cli@latest bundle  splitted/openapi.yml -o bundled

Just install node and the command will work.

**Comment by predic8** [comment]
Hi @paulhyo,
actually the OpenAPI parser in Membrane can resolve external references. So we are going to implement it.
