### ISSUE TITLE
 org.xml.sax.SAXParseException - Content is not allowed in prolog with valid wsdl + xsd files

### ISSUE THREAD

**Issue by paulhyo** [membrane/api-gateway#1341]
Hello,

I'm trying to validate my soap messages using the serviceProxy or soapProxy with a wsdl file + several xsd files. The WSDL und XSD files are valid and are used in our IBM Datapower Instances to validate SOAP-Messages. The same files can also be used in SoapUI for testing.

In Membrane, an _org.xml.sax.SAXParseException - Content is not allowed in prolog_ error with one of the XSD is produced during Start-Up.

Membrane version: 5.5.4

SOAP-Specification:
[vostra2-strafregister-v1-soap-specification-1.2.0.zip](https://github.com/user-attachments/files/17715206/vostra2-strafregister-v1-soap-specification-1.2.0.zip)

Proxies.xml
[proxies.xml.txt](https://github.com/user-attachments/files/17715100/proxies.xml.txt)

LOG:
[membrane-soap-error-log.txt](https://github.com/user-attachments/files/17715107/membrane-soap-error-log.txt)

Thank you!

**Comment by predic8** [comment]
Hi @paulhyo,
thanks for reporting the issue. The file eCH-0051-common-2-10-0.xsd starts with a byte order mark. The BOM consists of the byte sequence EF BB BF that is sometimes inserted to indicate the encoding of a text file. The image shows the byte sequence of the file.

<img width="971" alt="grafik" src="https://github.com/user-attachments/assets/215353c5-7781-41b2-b740-a6d117fdca2b">

If you remove the BOM from the file it will work. Just open it in VSC and change the encoding at the bottom from "UTF-8 with BOM" to "UTF-8" and save. It is the only file in your zip archive with BOM.

Unfortunately the XML parser library can not deal with the BOM. We will strip the BOM before parsing in a future Membrane version.

**Comment by rrayst** [comment]
@predic8 Membrane's GraphQL parser uses `org.apache.commons.io.input.BOMInputStream` for that purpose.

**Comment by predic8** [comment]
Thanks. I am writing a test right now. Maybe we can use the class also for XSDs and WSDLs.

**Comment by predic8** [comment]
@paulhyo thanks for reporting again.
#1341 fixes the issue.
