### ISSUE TITLE
Reduce log output

### ISSUE THREAD

**Issue by predic8** [membrane/api-gateway#1376]
Change from INFO to DEBUG:

´´´
14:37:54,756  INFO 34 RouterThread /127.0.0.1:64767 ProblemDetails:130 - type=user
title=Wrong path or method
,detail=This request was not accepted by Membrane. Please check HTTP method and path.
,extension={},.
14:37:54,893  INFO 34 RouterThread /127.0.0.1:64767 ProblemDetails:130 - type=user
title=Wrong path or method
,detail=This request was not accepted by Membrane. Please check HTTP method and path.
,extension={},.
14:38:01,049  INFO 34 RouterThread /127.0.0.1:64767 ProblemDetails:130 - type=user
title=Wrong path or method
,detail=This request was not accepted by Membrane. Please check HTTP method and path.
,extension={},.
14:38:05,995  INFO 34 RouterThread /127.0.0.1:64767 ProblemDetails:130 - type=user
title=Wrong path or method
,detail=This request was not accepted by Membrane. Please check HTTP method and path.
,extension={},.
14:43:03,052  INFO 35 RouterThread /127.0.0.1:64882 OpenAPIPublisherInterceptor:152 - OpenAPI with id fruitshop-v1-1 requested
´´´

**Comment by rrayst** [comment]
Let's discuss this please:

The message returned to the caller in Production Mode says "Generic Error. ID 76487263. For details, see log."

If the Log is empty, this does not make sense.

**Comment by predic8** [comment]
If there is a 404 that should also be communicated in production mode. Makes it sense to hide a 404?

**Comment by predic8** [comment]
I should have a look at production mode
