### ISSUE TITLE
OAuth2Resource: Sending token in request (without use of OAuth2Resource) breaks refreshing (only vague description available)

### ISSUE THREAD

**Issue by xorpherion** [membrane/api-gateway#311]
`INFO   | jvm 1    | 2018/02/14 15:50:43 | 15:50:43,188  WARN AbstractHttpHandler:89 - An exception occured while handling a request:
INFO   | jvm 1    | 2018/02/14 15:50:43 | java.lang.NullPointerException
INFO   | jvm 1    | 2018/02/14 15:50:43 |       at com.predic8.membrane.core.interceptor.oauth2.OAuth2ResourceInterceptor.refreshingOfAccessTokenIsNeeded(OAuth2ResourceInterceptor.java:316)
INFO   | jvm 1    | 2018/02/14 15:50:43 |       at com.predic8.membrane.core.interceptor.oauth2.OAuth2ResourceInterceptor.handleRequestInternal(OAuth2ResourceInterceptor.java:248)
INFO   | jvm 1    | 2018/02/14 15:50:43 |       at com.predic8.membrane.core.interceptor.oauth2.OAuth2ResourceInterceptor.handleRequest(OAuth2ResourceInterceptor.java:191)
INFO   | jvm 1    | 2018/02/14 15:50:43 |       at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeRequestHandlers(InterceptorFlowController.java:106)
INFO   | jvm 1    | 2018/02/14 15:50:43 |       at com.predic8.membrane.core.interceptor.UserFeatureInterceptor.handleRequest(UserFeatureInterceptor.java:43)
INFO   | jvm 1    | 2018/02/14 15:50:43 |       at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeRequestHandlers(InterceptorFlowController.java:106)
INFO   | jvm 1    | 2018/02/14 15:50:43 |       at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeHandlers(InterceptorFlowController.java:71)
INFO   | jvm 1    | 2018/02/14 15:50:43 |       at com.predic8.membrane.core.transport.http.AbstractHttpHandler.invokeHandlers(AbstractHttpHandler.java:70)
INFO   | jvm 1    | 2018/02/14 15:50:43 |       at com.predic8.membrane.core.transport.http.HttpServerHandler.process(HttpServerHandler.java:234)
INFO   | jvm 1    | 2018/02/14 15:50:43 |       at com.predic8.membrane.core.transport.http.HttpServerHandler.run(HttpServerHandler.java:119)
INFO   | jvm 1    | 2018/02/14 15:50:43 |       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
INFO   | jvm 1    | 2018/02/14 15:50:43 |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
INFO   | jvm 1    | 2018/02/14 15:50:43 |       at java.lang.Thread.run(Thread.java:745)`

external client negotiates a token on its own and sends the token to a resource that is protected by oauth2resource -> this takes the "no session, authorization header available" path

**Comment by predic8** [comment]
Too old. Please reopen if still relevant.
