### ISSUE TITLE
Set Header Interceptor

### ISSUE THREAD

**Issue by predic8** [membrane/api-gateway#368]
You can set header using groovy but it might comfortable to have an dedicated interceptor:

    <header name="foo" value="42"/>

It should be possible to use an expression language inside the value field. Something like:

    <header name="foo" value="${exc.request.headers['Bar']}"/>

or 

<header name="foo" value="${exc.properties.bar}"/>

Do we have alread an Expression Language, Should we use Groovy or and a language?

**Comment by t-burch** [comment]
As it seems this has been implemented using the SpEL previously so branch #368 is stale now.
