### ISSUE TITLE
GatekeeperClientInterceptor cleanup 

### ISSUE THREAD

**Issue by predic8** [membrane/api-gateway#454]
There are two GateKeeperClientInterceptor in two packages. One is not used. Can we delete some unused code?

com.predic8.membrane.core.sslinterceptor
com.predic8.membrane.core.interceptor.gatekeeper

**Comment by rrayst** [comment]
One is an SSLInterceptor, the other is an Interceptor.

**Comment by predic8** [comment]
Both classes only differ in a few lines. The duplicated code should be avoided.

**Comment by t-burch** [comment]
Refactor would require require SSLExchange to be refactored as well, it is currently not inheriting AbstractExchange
