### ISSUE TITLE
Documentation for Linux installation

### ISSUE THREAD

**Issue by rrayst** [membrane/api-gateway#461]
# How to install Membrane Service Proxy on Linux

In this example, we use Ubuntu 22.04.1 as a base system. Of course, in general, you can use any Linux distribution.

Run the following commands:

```
apt-get update

apt-get install -y unzip openjdk-19-jdk

cd /opt

curl -o membrane.zip -L https://github.com/membrane/service-proxy/releases/download/v5.0.1/membrane-service-proxy-5.0.1.zip

unzip membrane.zip

rm membrane.zip

ln -sf membrane-service-proxy-5.0.1 membrane-service-proxy

addgroup --system membrane

adduser --system --group membrane
```

## Configure the SystemD-integration

Create a file called `/etc/systemd/system/membrane.service` with the following content:

```
[Unit]
Description=Membrane
After=network-online.target
Requires=network-online.target

[Service]
ExecStart=/usr/bin/bash -c /opt/membrane-service-proxy/service-proxy.sh
WorkingDirectory=/opt/membrane-service-proxy
Restart=always
RestartSec=10s
TimeoutSec=60
User=membrane
Group=membrane

[Install]
WantedBy=multi-user.target  
```

## Configure Logging

For example, to log everything to stdout (which get's collected by SystemD and which can be monitored using `journalctl -u membrane.service`), replace `/opt/membrane-service-proxy/conf/log4j2.xml` by

```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration>
    <Appenders>
        <Console name="STDOUT" target="SYSTEM_OUT">
            <PatternLayout pattern="%d{ABSOLUTE} %5p %tid %tn %c{1}:%L - %m%n" />
        </Console>
    </Appenders>
    <Loggers>
        <Root level="info">
            <AppenderRef ref="STDOUT" />
        </Root>
    </Loggers>
</Configuration>
```

## Configure Membrane

To customize your installation, you would change `/opt/membrane-service-proxy/conf/proxies.xml` . In this demo, we use the default configuration.

## Start Membrane

Run the following commands:

```
systemctl daemon-reload

systemctl start membrane
```

## Check, whether Membrane started correctly

You might want to monitor the system log, or run

```
curl -v http://localhost:2000
```

## Activate auto-start for Membrane
Run the following command to tell SystemD to start Membrane when the machine boots:
```
systemctl enable membrane
```

## Ongoing tasks

* It is advised to keep Membrane up to date. 
* It is advised to keep Java up to date.
* It is advised to keep your base system up to date.

**Comment by christiangoerdes** [comment]
https://membrane-api.io/ - new subpoint

**Comment by christiangoerdes** [comment]
5.2.0 and renaming from service-proxy to api-gateway
