### ISSUE TITLE
Will socket proxies be supported ?

### ISSUE THREAD

**Issue by liyaojinli** [membrane/api-gateway#671]
I wonder when socket proxy will be supported in the future? Thanks

**Comment by rrayst** [comment]
Do you mean forwarding a TCP connection?

For a simple TCP connection, we currently have no plans.

For SSL-/TLS-based connections, you could do
```xml
<router>
	<sslProxy host="sample-service.predic8.de" port="1234">
		<target host="sample-backend.predic8.de" port="5678" />
	</sslProxy>
</router>
```

The `<sslProxy/>` forwards SSL-/TLS-based traffic **without** decrypting it. (Therefore, no content inspection/modifications can be configured in Membrane.) The `@host` attribute on the `<sslProxy/>` Element acts as an inbound filter: The incoming TLS connection (dest port 1234) has to indicate `sample-service.predic8.de` using TLS [SNI](https://datatracker.ietf.org/doc/html/rfc3546#section-3.1) for the sslProxy to be chosen in rule matching. The traffic is forwarded to `sample-backend.predic8.de:5678`.
