### ISSUE TITLE
Docker Hub Description Incorrect Command

### ISSUE THREAD

**Issue by t-burch** [membrane/api-gateway#711]
On the Docker Hub page for membrane, the quick start guide uses the command: `docker run -v proxies.xml:/opt/membrane/conf/proxies.xml -p 2000:2000 predic8/membrane`, when it should be `docker run -v proxies.xml:/opt/membrane/conf/ -p 2000:2000 predic8/membrane` for it to not fail because of "proxies.xml is not a directory."

**Comment by predic8** [comment]
Mac is:

docker run -v "$(pwd)/proxies.xml:/opt/membrane/conf/proxies.xml" -p 2000:2000 predic8/membrane

We have to consider the different OSs
