### ISSUE TITLE
full api-gateway naming migration

### ISSUE THREAD

**Issue by koin612** [membrane/api-gateway#741]
there are still some `service-proxy` namings in the project.

I think we should prioritise the names in the release to not cause confusion for the end user.

```sh
~/Downloads/membrane-api-gateway-5.2.0 via ☕ v17.0.7 
❯ grep -Rnw . -e 'service-proxy' | wc -l
     284
```

**Comment by predic8** [comment]
Renaming service-proxy.sh files will break a lot. Maybe we should wait till Version 6.0.

**Comment by christiangoerdes** [comment]
Tried it at Branch #741-api-gateway-naming-migration and all tests passed.
