### ISSUE TITLE
Logo ideas and discussion

### ISSUE THREAD

**Issue by koin612** [membrane/api-gateway#758]
I saw the Logo PR and was coming up with some alternative Ideas. 

I'd like to sketch them up and maybe someone more talented in this could try to finalize this

Both examples shall be clean and simple and not be messy/overloaded. Goal was to capture "Membrane Api Gateway" as an product less than a brand so there more details about the "api gateway" stuff.

If we take the Logo from the PR I think we should try to put the arrow up somehow? I think not knowing Membrane as product a downward arrow is associated negativly / downwards trendy?

What do you think @predic8 @rrayst 

![image](https://github.com/membrane/api-gateway/assets/8482235/be7ba67d-c45f-450c-8813-3db427370abf)
![image](https://github.com/membrane/api-gateway/assets/8482235/70717df7-13a1-4e52-a041-7b59ba4a0b70)

**Comment by predic8** [comment]
Thanks for the ideas. The direction of the arrows sounds logic to me. We can ask Torben to get creative with the ideas. Till then I would use the logo from the PR. With logo it looks a lot more mature.

**Comment by t-burch** [comment]
My fear is that people might mix up this iteration of the membrane logo with the markup logo, as our minds tend to simplify shapes and patterns. So a capital M + downwards arrow might be too general in a developer context. 
I like @koin612's ideas. The incoming/outgoing arrows would encompass membranes philosophy well, and additionally make it distinct enough for it to be unlikely to be mixed up with markdown etc.
The first option might be the best if we want to go for "brand recognition", the gate concept probably doesn't exist yet, whilst the letter type mix-in with arrows is possibly taken elsewhere.

**Comment by bridgerdier** [comment]
I agree the downwards arrow is a bit too generic. Maybe take the gate+arrows idea a step further and have two opposing horizontal arrows pass through the "gate". Possibly even fill the inside of the gate with the same color (solid or reduced opacity) for a more literal interpretation of Membrane

**Comment by Inphinitation** [comment]
I can try to make few concept designs

**Comment by t-burch** [comment]
I can try to make a couple concept designs
