### ISSUE TITLE
Should Membrane be listed as ACME capable client @ Let's Encrypt?

### ISSUE THREAD

**Issue by t-burch** [membrane/api-gateway#770]
Let's Encrypt has a list of ACME capable clients where anyone can submit their own through a pull request on their repository (https://letsencrypt.org/docs/client-options/). Should we submit Membrane as a way of gaining more users?

**Comment by predic8** [comment]
+1 
Good idea. Can you create a pull request there with a new category? API Gateway? Maybe you can post it here before?

**Comment by t-burch** [comment]
We can't make a new category but we can add it to the relatively compact list of "Projects integrating with Let's Encrypt".
But there's two questions now in response to their rules when adding new projects:
1. Does Membrane auto-renew certificates at a random time? (Random time after set renewal interval, so 2/3 of the certificates lifespan + 4:23)
   Let's Encrypt enforces this so that they don't get regular spikes of traffic at the top of the hour etc.
2. Everyone links to their documentation explaining how to set up ACME.
   Membrane does not have ACME documentation in SSL yet, I could add an example and a guide to membrane-api.io so we can link that page.

**Comment by predic8** [comment]
Create example first
"Membrane API Gateway" as Link in Projects.
