### ISSUE TITLE
request/response body not shown in adminConsole

### ISSUE THREAD

**Issue by rrayst** [membrane/api-gateway#790]
request/response bodies are not shown in adminConsole.

(5.2.0, examples/oauth2/membrane, http://localhost:9000 -> Calls -> POST /token )

**Comment by t-burch** [comment]
![image](https://github.com/membrane/api-gateway/assets/119930761/fcf84d6d-1358-45ea-84f4-f2e97ea36c7f)

This error appears on call details page.

![image](https://github.com/membrane/api-gateway/assets/119930761/d91ba448-f97b-4381-96f4-6537e58fb2d5)
