### ISSUE TITLE
keys.txt: please add "these are demo keys" comment

### ISSUE THREAD

**Issue by rrayst** [membrane/api-gateway#804]
please add a comment
```
# these are demo API keys, see examples/api-keys
```
on top of the `keys.txt` file.

**Comment by Inphinitation** [comment]
But the file is under test resources, shouldn't it be clear they're not keys to be used in production. A normal user would not find them. And we would need to implement a parser feature to understand comments

**Comment by tburch22** [comment]
But the keys are in the test resources folder, it should be clear they are not production keys. A normal user would not find them.
We would need an extra parser feature to ignore comments if we do add this line.

**Comment by rrayst** [comment]
* there is a file called `keys.txt` in the top level project directory: https://github.com/membrane/api-gateway/blob/master/keys.txt
* comments should definitely be possible in the file. many people use them to track "who added the api key?" "when was it added?" "because of which ticket?" etc

**Comment by christiangoerdes** [comment]
This file was for testing reasons and can be removed.
