### ISSUE TITLE
Make Validation of JWT Tokens optional

### ISSUE THREAD

**Issue by predic8** [membrane/api-gateway#908]
Like API-Key plugin. Validation can be set to optional. So an endpoint is with and without token reachable. If there is a token, it should be validated an the header fields should be populated accordingly.

*Attention:* It should not be possible to send those headers as a client

**Comment by rrayst** [comment]
possibly as an attribute to `<requireAuth .../>`

**Comment by predic8** [comment]
Is this done? It is already in the lastet release?
