### ISSUE TITLE
`<accessLog/>` should escape header values

### ISSUE THREAD

**Issue by rrayst** [membrane/api-gateway#957]
maybe put everything in quotes `"` and escape quotes `"` to `\"`, if they are contained in the value

**Comment by predic8** [comment]
Maybe httpd could be an example:

'''
In addition, log files may contain information supplied directly by the client, without escaping. Therefore, it is possible for malicious clients to insert control-characters in the log files, so care must be taken in dealing with raw logs."
'''

And you are right, the " is the only character that is escaped: 

'''
The quote character (") must be escaped by placing a backslash before it to prevent it from being interpreted as the end of the format string. The format string may also contain the special control characters "\n" for new-line and "\t" for tab.
'''

See:
https://httpd.apache.org/docs/2.4/logs.html

**Comment by predic8** [comment]
?foo=ab"c => ... "ab\"c" ...
