### ISSUE TITLE
REST Tutorial: Check migration from thomas-bayer.com to api.predic8.de

### ISSUE THREAD

**Issue by predic8** [membrane/api-gateway#972]
https://membrane-api.io/tutorials/rest/

Ask Thomas

**Comment by predic8** [comment]
Also change router/proxies.xml accordingly and update the distribution/tutorial/rest Tutorial and the examples/tutorial Test

**Comment by christiangoerdes** [comment]
All `TutorialRestStepsTest` Tests passed with the old configurations, but they shouldn't have. For example
```   
get("http://localhost:2001/shop/products/")
                .then()
                .assertThat()
                    .contentType(APPLICATION_JSON)
                    .body("meta.count",greaterThan(10));          
```
This test passes even when the actual response is:
```
type: "http://membrane-api.io/error/gateway"
title: "This request was not accepted by Membrane. Please check HTTP method and path."
```
